before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -X github.com/sachaos/ac-deck/cmd.version={{.Version}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: sachaos
    name: homebrew-ac-deck
  folder: Formula
  homepage: https://github.com/sachaos/ac-deck
  description: Unofficial CLI for AtCoder users
  skip_upload: auto
  test: |
    system "#{bin}/ac-deck", "--version"
