name: Docker
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        environment:
          - gcc
          - python2
          - python3
          - python3-old
      fail-fast: false
    name: Build & Push sachaos/atcoder-${{ matrix.environment }} Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sachaos/atcoder-${{ matrix.environment }}
          path: docker/${{ matrix.environment }}
          tags: latest
