name: Docker
on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: Build Image & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sachaos/atcoder-gcc
          path: docker/gcc
          tags: latest
